import { useCallback, useEffect, useState } from 'react'
import {
  Background,
  BackgroundVariant,
  ReactFlow,
  useEdgesState,
  useNodesState,
  type Node,
  type NodeMouseHandler,
} from '@xyflow/react'
import '@xyflow/react/dist/style.css'

import { Badge } from '@/components/ui/badge'
import { Card } from '@/components/ui/card'
import { RectNode } from '@/features/workflow-builder/nodes/rect-node'
import { CircleNode } from '@/features/workflow-builder/nodes/circle-node'
import { ConditionNode } from '@/features/workflow-builder/nodes/condition-node'
import { graphToFlow } from '@/features/workflow-builder/graph-to-flow'
import { NlEditBar } from '@/features/workflow-generator/nl-edit-bar'
import { NlEditDiffCard } from '@/features/workflow-generator/nl-edit-diff-card'
import { useWorkflow } from '@/hooks/use-workflows'
import type { Workflow, WorkflowSource } from '@/types'

const nodeTypes = {
  rect: RectNode,
  circle: CircleNode,
  condition: ConditionNode,
}

const SOURCE_LABEL: Record<WorkflowSource, { text: string; variant: 'neutral' | 'agent' }> = {
  manual: { text: 'Built manually', variant: 'neutral' },
  generated: { text: '✨ Generated by AI', variant: 'agent' },
  hybrid: { text: '✨ AI-generated, hand-edited', variant: 'agent' },
}

/** Renders a REAL, backend-compiled workflow (Phase 7's output, or any
 * workflow fetched by id) — read-only canvas (no drag/save/run wiring
 * yet, that remains separate follow-up work), but natural-language
 * *editing* (§16.11) is fully wired: the NlEditBar below kicks off a real
 * diff-review-apply cycle against this workflow. */
export function RealWorkflowView({ workflowId }: { workflowId: string }) {
  const { data: workflow, isLoading } = useWorkflow(workflowId)

  if (isLoading || !workflow) {
    return <div className="p-6 text-[13px] text-fg-dim">Loading workflow…</div>
  }

  return <RealWorkflowCanvas workflow={workflow} />
}

function RealWorkflowCanvas({ workflow }: { workflow: Workflow }) {
  const { nodes: initialNodes, edges: initialEdges } = graphToFlow(
    workflow.graph ?? { nodes: [], edges: [] },
  )
  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes)
  const [edges, setEdges] = useEdgesState(initialEdges)
  const [selected, setSelected] = useState<Record<string, unknown> | null>(null)
  const [editRequestId, setEditRequestId] = useState<string | null>(null)

  // The canvas mounts once per workflow id, but an applied NL edit bumps
  // `version` and refetches the SAME workflow — re-derive the graph
  // whenever that happens rather than only ever showing the graph as it
  // was on first render.
  useEffect(() => {
    const { nodes: freshNodes, edges: freshEdges } = graphToFlow(
      workflow.graph ?? { nodes: [], edges: [] },
    )
    setNodes(freshNodes)
    setEdges(freshEdges)
    setSelected(null)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [workflow.id, workflow.version])

  const onNodeClick = useCallback<NodeMouseHandler<Node>>((_event, node) => {
    setSelected(node.data as Record<string, unknown>)
  }, [])

  const source = SOURCE_LABEL[workflow.source ?? 'manual']

  return (
    <div>
      <div className="mb-4 flex flex-wrap items-center justify-between gap-4">
        <div>
          <h2 className="text-[17px] font-semibold">{workflow.name}</h2>
          <div className="mt-1 flex items-center gap-2.5 text-xs text-fg-faint">
            <Badge variant={source.variant}>{source.text}</Badge>
            <span>v{workflow.version}</span>
            <span>·</span>
            <span>trigger: {workflow.triggerType}</span>
            <span>·</span>
            <span>{workflow.isActive ? 'active' : 'inactive — review before activating'}</span>
          </div>
        </div>
        <NlEditBar
          workflowId={workflow.id}
          disabled={Boolean(editRequestId)}
          onStarted={setEditRequestId}
        />
      </div>

      {editRequestId && (
        <div className="mb-4">
          <NlEditDiffCard requestId={editRequestId} onResolved={() => setEditRequestId(null)} />
        </div>
      )}

      <div className="grid grid-cols-[minmax(0,1fr)_280px] items-start gap-4">
        <Card className="overflow-hidden">
          <div style={{ height: 360 }}>
            <ReactFlow
              nodes={nodes}
              edges={edges}
              onNodesChange={onNodesChange}
              onNodeClick={onNodeClick}
              nodeTypes={nodeTypes}
              nodesConnectable={false}
              fitView
              fitViewOptions={{ padding: 0.15 }}
              proOptions={{ hideAttribution: true }}
              defaultEdgeOptions={{ style: { stroke: 'var(--border)', strokeWidth: 1.6 } }}
            >
              <Background variant={BackgroundVariant.Dots} gap={16} size={1} color="var(--border)" />
            </ReactFlow>
          </div>
        </Card>

        <Card className="flex flex-col gap-3 p-3.5">
          {!selected ? (
            <div className="text-[13px] text-fg-dim">Select a node to inspect it.</div>
          ) : (
            <>
              <div className="text-[15px] font-semibold">{String(selected.label)}</div>
              <div className="text-[12px] text-fg-faint">{String(selected.sub)}</div>
              <div className="flex flex-col gap-1.5 border-t border-border pt-2.5">
                {Object.entries(selected)
                  .filter(([key]) => !['label', 'sub', 'kind'].includes(key))
                  .map(([key, value]) => (
                    <div key={key} className="flex items-baseline justify-between gap-2 text-[12px]">
                      <span className="text-fg-faint">{key}</span>
                      <span className="truncate font-mono font-medium">{String(value)}</span>
                    </div>
                  ))}
              </div>
            </>
          )}
        </Card>
      </div>
    </div>
  )
}
