"""add workflow generation requests

Revision ID: 22572af97ee9
Revises: ebe58ea139b7
Create Date: 2026-08-08 03:39:01.341325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22572af97ee9'
down_revision: Union[str, Sequence[str], None] = 'ebe58ea139b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_generation_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('target_workflow_id', sa.Uuid(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('clarifying_questions', sa.JSON(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('plan', sa.JSON(), nullable=True),
    sa.Column('diff', sa.JSON(), nullable=True),
    sa.Column('missing_components', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['target_workflow_id'], ['workflows.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_generation_requests_org_id'), 'workflow_generation_requests', ['org_id'], unique=False)
    # batch_alter_table rather than plain add_column/create_foreign_key —
    # SQLite has no native ALTER TABLE ADD CONSTRAINT at all (unlike
    # Postgres), so adding the FK requires the copy-and-move strategy batch
    # mode provides. This is a no-op wrapper on Postgres (emits the same
    # plain ALTER statements), so it's safe to always use here.
    with op.batch_alter_table('workflows') as batch_op:
        batch_op.add_column(
            sa.Column('source', sa.String(length=20), nullable=False, server_default='manual')
        )
        batch_op.add_column(sa.Column('generation_request_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            'fk_workflows_generation_request_id',
            'workflow_generation_requests',
            ['generation_request_id'],
            ['id'],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows') as batch_op:
        batch_op.drop_constraint('fk_workflows_generation_request_id', type_='foreignkey')
        batch_op.drop_column('generation_request_id')
        batch_op.drop_column('source')
    op.drop_index(op.f('ix_workflow_generation_requests_org_id'), table_name='workflow_generation_requests')
    op.drop_table('workflow_generation_requests')
    # ### end Alembic commands ###
